config/routes.rb
Rails.application.routes.draw do
  resources :reviews

  devise_for :users
  devise_for :installs
  root "pages#home"
  get "about" => "pages#about" #Creates about_path
  get "agents" => "pages#agents"
  get "signup" => "pages#signup"
  get "login" => "pages#login"  

  

end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def agents
  end

  def login
  end

  def signup
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  def index
    @reviews = Review.all
  end

  def show
  end


  def new
    @review = Review.new
  end

  def edit
  end

  def create
    @review = Review.new(review_params)


      if @review.save
        redirect_to @review, notice: 'Review was successfully created.'
      else
        render :new
      end

  end

  def update
    
      if @review.update(review_params)
        redirect_to @review, notice: 'Review was successfully updated.'
      else
        render :edit
        end
    
  end

  def destroy
    @review.destroy
      redirect_to reviews_url, notice: 'Review was successfully destroyed.'    
  end

  private

    def set_review
      @review = Review.find(params[:id])
    end

def review_params
      params.require(:review).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Vurdera", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Agents", agents_path %></li>
        <li><%= link_to "About", about_path %></li>

        <% if user_signed_in? %>
        <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
        

         <% if user_signed_in? %>
         <li class="dropdown">
         <a href="#"  data-toggle="dropdown">Dit Vurdera <span class="caret"></span></a>


         <ul class="dropdown-menu" role="menu">
          <li class="dropdown"><%= link_to "Skift kodeord", edit_user_registration_path, class: "dropdown-toggle" %></li>
          <li class="dropdown"><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-toggle" %></li>
        </ul>
        </li>
         <% else %>
         <li><%= link_to "Login", new_user_session_path %></li>
         
         <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<%= render "layouts/header" %>
	<div class="container">
	<% flash.each do |name, msg| %>
  <%= content_tag(:div, msg, class: "alert alert-info") %>
	<% end %>
	<%= yield %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>

<p>I am working on the pinteresting app. I hope it works! :P<p>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h2> Rate your local Real Estate agent</h2>
	<BR>

 <% if user_signed_in? %>
 	Velkommen, Du er nu klar til at vurdere din lokale ejendomsmægler.

 <% else %>

	<p> 
	<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	</p>

 <% end %>


</div>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>

      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
  
  
  <div class="form-group">  
    <div class="field">
      <%= f.label :description, class: "" %><br>
    </div>
    <div class="form-group">
      <%= f.text_field :description, class: "form-control" %>
    </div>
    <div class="actions">
      <%= f.submit "Jeg er færdig", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
		<h3>Rediger din vurdering</h3>
	</div>

	<div class="panel-body">
		<%= render 'form' %>
	</div>

	<div class="panel-footer">
		<%= link_to 'Vis vurdering', @review %> |
		<%= link_to 'Tilbage', reviews_path %>
	</div>
</div>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.description %></td>
        <td><%= link_to 'Vis', review %></td>
        <td><%= link_to 'Rediger', edit_review_path(review) %></td>
        <td><%= link_to 'Slet', review, method: :delete, data: { confirm: 'Er du sikker?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
		<h3>Skriv din vurdering</h3>
	</div>

	<div class="panel-body">
		<%= render 'form' %>
	</div>

	<div ="panel-footer">
		<%= link_to 'Tilbage', reviews_path %>
	</div>

</div>

app/views/reviews/show.html.erb
<div class="panel panel-default">
		<div class="panel-heading">
			 <h3>Vurdering</h3>
		</div>
		
		<div class="panel-body">
			<p id="notice"><%= notice %></p>
			<p>
		 	<%= @review.description %>
			</p>
		</div>

		<div class="panel-footer">

				<%= link_to 'Rediger vurdering', edit_review_path(@review) %> |
				<%= link_to 'Tilbage', reviews_path %>
		</div>
</div>